name: Monorepo release
run-name: Monorepo release ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'patch'

jobs:
  releasecall:
    uses: AloisJasa/.github/.github/workflows/monorepo_release.yml@main
    name: Monorepo release
    with:
      version: ${{ inputs.version }}
    secrets:
      gh-token: ${{ secrets.ACCESS_TOKEN }}
