name: Monorepo release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'patch'

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: git config --global user.name "GitHub Action"
      - run: git config --global user.email "action@github.com"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Stage Check
        id: stage
        shell: bash
        run: |
          if [ "${{ inputs.version }}" == 'patch' ]; then
            echo "stage=patch" >> $GITHUB_OUTPUT;
          elif [ "${{ inputs.version }}" == 'minor' ]; then
            echo "stage=release" >> $GITHUB_OUTPUT;
          elif [ "${{ inputs.version }}" == 'major' ]; then
            echo "stage=release" >> $GITHUB_OUTPUT;
          fi

      - name: Release
        run: vendor/bin/monorepo-builder release ${{ inputs.version }} --stage ${{ steps.stage.outputs.stage}}
