name: Monorepo release
run-name: Monorepo release ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'patch'

jobs:
  releasecall:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - uses: AloisJasa/.github/.github/workflows/p7-monorepo-release@main
        with:
          version: ${{ inputs.version }}
          gh-token: ${{ secrets.ACCESS_TOKEN }}
          dry-run: 'true'
