name: Monorepo release
run-name: Monorepo release ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'patch'

jobs:
  releasecall:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN}}

      - uses: AloisJasa/.github/.github/actions/p7-monorepo-release@main
        with:
          version: ${{ inputs.version }}
          gh-token: ${{ secrets.ACCESS_TOKEN }}
