name: Publish release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.0'

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

env:
  DRC: ${{ vars.PROJECT }}

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Vytvoření nového releasu
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AloisJasa/monorepo-split-playground
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: AloisJasa/.github/.github/actions/p7-release-drafter@main
        with:
          tag: ${{ github.ref_name }}
          publish: true
          gh-token: ${{ secrets.ACCESS_TOKEN }}
