name: Split Monorepo v2 - forcepush

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - main
      - 'v[0-9]+.[0-9]+'

concurrency:
  group: split_monorepo-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  split-branch:
    uses: AloisJasa/.github/.github/workflows/split_monorepo_git-filter.yaml@main
    name: Split branch
    strategy:
      fail-fast: false
      matrix:
        package:
          - monorepo-split-playground-sub1
          - monorepo-split-playground-sub2
    with:
      package: ${{ matrix.package }}
      organization: "aloisjasa"
      force: ${{ inputs.force == 'true' }}
      push-tags:  ${{ github.ref != 'refs/heads/main' }}
    secrets:
      gh-token: ${{ secrets.ACCESS_TOKEN }}
